" from https://vi.stackexchange.com/questions/4141/how-to-indent-as-spaces-instead-of-tab/4175#4175
" tabstop:          Width of tab character
" softtabstop:      Fine tunes the amount of white space to be added
" shiftwidth        Determines the amount of whitespace to add in normal mode
" expandtab:        When this option is enabled, vi will use spaces instead of tabs
" I choose tabs to be 4 characters long to distinguish them from my two-space
" indent style
set tabstop     =4
set softtabstop =2
set shiftwidth  =2
set expandtab

" visible characters:
" https://vi.stackexchange.com/questions/422/displaying-tabs-as-characters
set list
set listchars=tab:␉·,trail:␠
"set listchars=eol:⏎,tab:␉·,trail:␠
"set listchars=eol:¬,tab:▸],trail:␠
"set listchars=eol:·,tab:>],trail:%

" smartcase matching - lowercase matches any case. Any casing matches only
" that casing:
" https://stackoverflow.com/a/2288438
set ignorecase
set smartcase

highlight ColorColumn ctermbg=cyan guibg=blue
let g:EditorConfig_max_line_indicator = "exceeding"

" I spend a lot of time typing q when I meant :q
map q :q

" Mouse scroll and click is *nice*
" https://stackoverflow.com/questions/7225057/use-mouse-scroll-wheel-in-vim
" https://unix.stackexchange.com/questions/139578/copy-paste-for-vim-is-not-working-when-mouse-set-mouse-a-is-on
" https://superuser.com/questions/1365832/how-to-enable-both-this-vim-feature-mouse-cursor-move-and-paste-with-middle-mou
" https://forum.manjaro.org/t/unable-to-paste-text-into-vim-using-mouse-middle-click/110323/5
set mouse=nv
set selectmode+=mouse

" wq is cool, but sometimes I type it as qw, and that should work too.
" Unfortunately, this is apparently more complicated than it seems
" see https://stackoverflow.com/questions/3878692/how-to-create-an-alias-for-a-command-in-vim
" Especially the commentor who wrote his own tool for this, who clarifies that
" vim doesn't let you create user-defined commands which start with a
" lower-case letter
" :command qw wq

" Respect XDG_ variables
" loosly based on https://github.com/sds/.vim/blob/master/xdg.vim
" which is itself based on https://github.com/kaleb/vim-files/blob/master/xdg.vim
if empty($XDG_STATE_HOME)
  let $XDG_STATE_HOME = $HOME.'/.local/state'
endif
if empty($XDG_CONFIG_HOME)
  let $XDG_CONFIG_HOME = $HOME.'/.config'
endif

" Automatically start Obsession without concatenating the status line (does cause the previous status line to be lost)
" https://vi.stackexchange.com/questions/8876/echo-message-on-startup-without-prompting
" TODO: don't do this on temporary files (especially the git commit message ones)
" TODO: when entering vim with no args, instead restore this session (this is
" currently accomplished via an indirection function)
" TODO: include quickfix file into the session. Potentially with https://vi.stackexchange.com/questions/38545/how-to-save-quickfix-list-per-neovim-session-using-mksession
" TODO: somehow, there's a terminal-width-dependent thing that says "Press
" ENTER or type command to continue". I wish that didn't happen
" (Update: it might be related to vim's messages or more-prompt help topics)
autocmd VimEnter * Obsession $XDG_STATE_HOME/vim/jake-autosaved-session

" preserve edit position,
" see https://stackoverflow.com/questions/7894330/preserve-last-editing-position-in-vim/7894493#7894493
source $VIMRUNTIME/vimrc_example.vim

" disable the textwidth setting in /usr/share/vim/vim82/vimrc_example.vim
" (it's annoying, and I don't like it)
augroup vimrcEx
  " Clear the contents of this group
  au!
augroup END
" Delete the group, for cleanliness
augroup! vimrcEx


" stash temporary files in ~ (modified to respect XDG, above)
" https://stackoverflow.com/questions/743150/how-to-prevent-vim-from-creating-and-leaving-temporary-files/61585014#61585014
set undofile
set undolevels=1000         " How many undos
set undoreload=10000        " number of lines to save for undo

set backup                           " enable backups
set swapfile                         " enable swaps
set undodir=$XDG_STATE_HOME/vim/undo      " undo files
set backupdir=$XDG_STATE_HOME/vim/backup  " backups
set directory=$XDG_STATE_HOME/vim/swap    " swap files
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" This is cargo-culted from https://github.com/tpope/vim-git/blob/master/ftdetect/git.vim
" I did at least figure out how to inline a function, and what au means
autocmd BufNewFile,BufRead $XDG_CONFIG_HOME/git/work-email let &filetype = "gitconfig"
autocmd BufNewFile,BufRead *.bash let &filetype = "bash"

" Make those folders automatically if they don't already exist.
if !isdirectory(expand(&undodir))
    call mkdir(expand(&undodir), "p")
endif
if !isdirectory(expand(&backupdir))
    call mkdir(expand(&backupdir), "p")
endif
if !isdirectory(expand(&directory))
    call mkdir(expand(&directory), "p")
endif
