" from https://vi.stackexchange.com/questions/4141/how-to-indent-as-spaces-instead-of-tab/4175#4175
" tabstop:          Width of tab character
" softtabstop:      Fine tunes the amount of white space to be added
" shiftwidth        Determines the amount of whitespace to add in normal mode
" expandtab:        When this option is enabled, vi will use spaces instead of tabs
" I choose tabs to be 4 characters long to distinguish them from my two-space
" indent style
set tabstop     =4
set softtabstop =2
set shiftwidth  =2
set expandtab
" TODO: it'd be cool if I could use tab to insert spaces in comments while
" preserving tab characters in the rest of the source.
"           ex: this line's indenting. Works in vimrc, but not bash files
"               (We're respecing editorconfig, but it's still... comments)

" visible characters:
" https://vi.stackexchange.com/questions/422/displaying-tabs-as-characters
set list
set listchars=tab:␉·,trail:␠
"set listchars=eol:⏎,tab:␉·,trail:␠
"set listchars=eol:¬,tab:▸],trail:␠
"set listchars=eol:·,tab:>],trail:%

" smartcase matching - lowercase matches any case. Any casing matches only
" that casing:
" https://stackoverflow.com/a/2288438
set ignorecase
set smartcase

" I have no idea why this is necessary, but my home vim just randomly started
" reading from ron, but lying about it (`:colorscheme` reports default,
" g:colors_name is unset)
" My default is somehow reading from ron? But not /usr/share/vim/vim82/colors/ron.vim, that's safe
colorscheme default

" This prevents synload from clobbering my custom highlight colors between (my best
" guess) the time this file is loaded and the edited file is loaded.
" TODO: that probably means I just need to write my own color scheme to be
" used globally instead, I guess.
let g:colors_name = ""
highlight DiffChange ctermbg=None
highlight Search ctermbg=blue ctermfg=black

highlight ColorColumn ctermbg=cyan guibg=blue
let g:EditorConfig_max_line_indicator = "exceeding"

" I spend a lot of time typing q when I meant :q
" TODO: what if I mapped this to "clear the search, but if there's no search,
" then do :q". Can I do that? The relevant variable looks like @/ thanks to
" https://stackoverflow.com/questions/657447/vim-clear-last-search-highlighting
" nb: less maps the 'clear search' action to ESC-u
map q :q

" Space should pagedown, like how less does it (otherwise, it's 'one space
" forward', which isn't helpful to me)
" TODO: I have a plugin managing this, which I'm not as happy with.
" What I'd like is a behavior like "If my prior motion was left/right, space
" is one to the right. If my prior motion was up/down by a single line, space
" mirrors that. Otherwise, page by a page"
noremap <space> <C-d>

" Mouse scroll and click is *nice*, but it needs a modifier (Shift) pressed to
" get the old terminal behavior, and the selection doesn't seem to grab
" newlines, for some reason?
" https://stackoverflow.com/questions/7225057/use-mouse-scroll-wheel-in-vim
" https://unix.stackexchange.com/questions/139578/copy-paste-for-vim-is-not-working-when-mouse-set-mouse-a-is-on
" https://superuser.com/questions/1365832/how-to-enable-both-this-vim-feature-mouse-cursor-move-and-paste-with-middle-mou
" https://forum.manjaro.org/t/unable-to-paste-text-into-vim-using-mouse-middle-click/110323/5
" TODO: I'd like a way to ask vim to simply ignore some mouse actions, but it
" doesn't seem doable. You'd need a mechanism for vim to have non-modified
" mouse clicks 'go to the xterm' (per :help terminal-mouse)
" This allows vim to look at mouse activity while I'm in (n)ormal, (v)isual,
" and (i)nsert contexts. Specifically, this excludes (c)ommand (and some misc. ones)
" which means you can get selection by going to :-command mode (like :wq)
" without having to hold Shift.
" NB: modeless-selection is the name for when vim emulates the selection style
" I'm used to. But it ends up not copying newline characters, so it's just a
" blob of chars - this is Windows Terminal's behavior, which can be disabled
" by turning on "Automatically copy selection to clipboard" in the
" settings/interaction menu (because then I don't have to hold shift while
" clicking, which procs the singleLine behavior of the copy command, below)
" https://github.com/microsoft/terminal/blob/ef96e225da6b0df496390eed9fe31dc7e434a939/src/cascadia/TerminalControl/ControlCore.cpp#L1242
" And there might be something to learn by trying to figure out this page:
" https://vim.fandom.com/wiki/Using_the_mouse_for_Vim_in_an_xterm
set mouse=nv
set ttymouse=xterm2 " more-responsive mouse tracking in the selection
" Potentially helps with copying into X?
" set clipboard+=unnamed

" from https://stackoverflow.com/questions/4911093/vim-change-mouse-click-behavior
" toggle between terminal and vim mouse
" (Abuse ternary to flip from nv -> off -> all -> off)
map <silent><F12> :let &mouse=(&mouse == ""?"a":"")<CR>:call ShowMouseMode()<CR>
imap <silent><F12> :let &mouse=(&mouse == ""?"a":"")<CR>:call ShowMouseMode()<CR>
function ShowMouseMode()
    if (&mouse == 'a')
        echo "mouse-vim"
    else
        echo "mouse-xterm"
    endif
endfunction


" wq is cool, but sometimes I type it as qw, and that should work too.
" Unfortunately, this is apparently more complicated than it seems
" see https://stackoverflow.com/questions/3878692/how-to-create-an-alias-for-a-command-in-vim
" Especially the commentor who wrote his own tool for this, who clarifies that
" vim doesn't let you create user-defined commands which start with a
" lower-case letter
" :command qw wq

" Respect XDG_ variables
" loosly based on https://github.com/sds/.vim/blob/master/xdg.vim
" which is itself based on https://github.com/kaleb/vim-files/blob/master/xdg.vim
if empty($XDG_STATE_HOME)
  let $XDG_STATE_HOME = $HOME.'/.local/state'
endif
if empty($XDG_CONFIG_HOME)
  let $XDG_CONFIG_HOME = $HOME.'/.config'
endif

" Automatically start Obsession without concatenating the status line (does cause the previous status line to be lost)
" https://vi.stackexchange.com/questions/8876/echo-message-on-startup-without-prompting
" TODO: don't do this on temporary files (especially the git commit message ones)
" TODO: when entering vim with no args, instead restore this session (this is
" currently accomplished via an indirection function)
" TODO: include quickfix file into the session. Potentially with https://vi.stackexchange.com/questions/38545/how-to-save-quickfix-list-per-neovim-session-using-mksession
" TODO: somehow, there's a terminal-width-dependent thing that says "Press
" ENTER or type command to continue". I wish that didn't happen
" (Update: it might be related to vim's messages or more-prompt help topics)
autocmd VimEnter * Obsession $XDG_STATE_HOME/vim/jake-autosaved-session
" TODO: it'd be nice, if we resumed an existing session, to have vim print the
" filenames from that session to stdout (stderr?) when we exit

" preserve edit position,
" see https://stackoverflow.com/questions/7894330/preserve-last-editing-position-in-vim/7894493#7894493
source $VIMRUNTIME/vimrc_example.vim

" disable the textwidth setting in /usr/share/vim/vim82/vimrc_example.vim
" (it's annoying, and I don't like it)
augroup vimrcEx
  " Clear the contents of this group
  au!
augroup END
" Delete the group, for cleanliness
augroup! vimrcEx


" stash temporary files in ~ (modified to respect XDG, above)
" https://stackoverflow.com/questions/743150/how-to-prevent-vim-from-creating-and-leaving-temporary-files/61585014#61585014
set undofile
set undolevels=1000         " How many undos
set undoreload=10000        " number of lines to save for undo

set backup                           " enable backups
set swapfile                         " enable swaps
set undodir=$XDG_STATE_HOME/vim/undo      " undo files
set backupdir=$XDG_STATE_HOME/vim/backup  " backups
set directory=$XDG_STATE_HOME/vim/swap    " swap files
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" This is cargo-culted from https://github.com/tpope/vim-git/blob/master/ftdetect/git.vim
" I did at least figure out how to inline a function, and what au means
" TODO: what values can filetype take?
" TODO: Thanks, past Jake for knowing what au means. Care to share with the class?
" TODO: vimpolyglot doesn't have a solution for the .cpy files from rmkit
autocmd BufNewFile,BufRead .mrconfig let &filetype = "gitconfig"
autocmd BufNewFile,BufRead $XDG_CONFIG_HOME/git/work-config let &filetype = "gitconfig"
autocmd BufNewFile,BufRead $XDG_CONFIG_HOME/aws/config let &filetype = "dosini"
autocmd BufNewFile,BufRead $XDG_CONFIG_HOME/aws/cli/alias let &filetype = "gitconfig" " NOT VALID, but better than dosini
autocmd BufNewFile,BufRead *.bash let &filetype = "bash"
autocmd BufNewFile,BufRead *.dockerfile let &filetype = "dockerfile"
autocmd BufNewFile,BufRead *.Jenkinsfile,*.jenkinsfile,*Jenkinsfile* let &filetype= "Jenkinsfile"

" Make those folders automatically if they don't already exist.
if !isdirectory(expand(&undodir))
    call mkdir(expand(&undodir), "p")
endif
if !isdirectory(expand(&backupdir))
    call mkdir(expand(&backupdir), "p")
endif
if !isdirectory(expand(&directory))
    call mkdir(expand(&directory), "p")
endif
