" My (Jake's) custom color file - a place to keep my color preferences once
" they deviate from vim's defaults.
" This file is based on vim's default color file default.vim, with guidance
" from the other color files "Generated by Colortemplate v2.2.3"
" and https://vi.stackexchange.com/questions/2782/how-can-i-create-my-own-colorscheme

" default.vim's highlight clearing:
hi clear Normal
set bg&
hi clear

" Load the syntax highlighting defaults, if it's enabled.
if exists("syntax_on")
  syntax reset
endif

" My color
let g:colors_name = 'jake'


" The default on this is super unreadable (yellow on white)
highlight DiffChange ctermbg=None

" Default search highlight is just yellow background.
" That washes out white or yellow text, rendering it unreadable
" It's also useful to change to a dark-ish color even if we include a fg
" color - it's also good to contrast to the cursor itself.
highlight Search ctermbg=blue ctermfg=black

" this is a better calming color
highlight ColorColumn ctermbg=cyan guibg=blue

" vim: sw=2
