" My (Jake's) custom color file - a place to keep my color preferences once
" they deviate from vim's defaults.
" This file is based on vim's default color file default.vim, with guidance
" from the other color files "Generated by Colortemplate v2.2.3"

" default.vim's highlight clearing:
hi clear Normal
set bg&
hi clear

" Load the syntax highlighting defaults, if it's enabled.
if exists("syntax_on")
  syntax reset
endif

" My color
let g:colors_name = 'jake'


" The default on this is super unreadable (yellow on white)
highlight DiffChange ctermbg=None

" Default search highlight color washes out over white or yellow text
highlight Search ctermbg=blue ctermfg=black

" this is a better calming color
highlight ColorColumn ctermbg=cyan guibg=blue

" vim: sw=2
